name: Test Builds
on:
  push:
    branches:
      - ["main", "nightly"]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['9', '11', '17', '20']

    name: Java ${{ matrix.java }} sample

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean untracked files
        run: git clean -fX

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Build and package JavaCrypt
        run: |
          javac -Xlint:unchecked ./javacrypt/MyCryptMain.java
          jar cfm JavaCrypt.jar ./javacrypt/makefile.txt javacrypt/*.class

      - name: Clean untracked files
        run: git clean -fX
